- hosts: localhost
  connection: local

  tasks:
      
    - name: Fetch Jitsi Role
      git:
        repo: https://ro:hBsT-FmxtXp-zeRt8Dq4@pwslab.org/ansible/jitsi-playbook.git
        dest: /root/.ansible/roles/pwslab.jitsi
        version: master
        force: yes


    - name: Installing Jitsi
      include_role:
        name: pwslab.jitsi